name: Sync main to develop

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create and Merge PR
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          pr_url=$(gh pr create --fill)
          gh pr merge $pr_url --rebase
